### ISSUE TITLE
Idea behind your model (which paper is your model based)

### ISSUE THREAD

**Issue by chuhailinh** [Huffon/sentence-compressor#4]
I want to know which paper you build your model or you create from scratch not based any paper

**Comment by Huffon** [comment]
There are various papers dealing with Sentence Compression task.
Check [Laser Tagger](https://github.com/google-research/lasertagger) !

**Comment by chuhailinh** [comment]
> There are various papers dealing with Sentence Compression task.
> Check [Laser Tagger](https://github.com/google-research/lasertagger) !

Following your code, i undertand that your model use transformers based machine translation with input is source sentence and output is compress sentence. Is it right? And there are any technique in your code different from transformers model?
